### ISSUE TITLE
agile_led_create可能导致的内存泄漏问题和链表的创建

### ISSUE THREAD

**Issue by HikerPan** [loogg/agile_led#2]
如果同一个pin，多次调用agile_led_create，因为agile_led_t *led = (agile_led_t *)rt_malloc(sizeof(agile_led_t));调用之前没有判断pin是否被占用，会导致再次对该pin执行creat，而上一次create的led内存未被释放掉，所以可能导致内存泄漏。
当然，您在example中首先判断了led是否为NULL，但如果在create内部做好判断并返回相应提示将更加健壮。
另外，建议led 加入链表放在create中，从链表中删除放在delete中，同时active enable放在start中，disable放在stop中，这样逻辑更清晰。
button中存在同样问题。
led的软件我已经修改完了，您要是感兴趣可以传给你看看

**Comment by loogg** [comment]
git上提交一下pull request吧



---原始邮件---
发件人: "HikerPan"<notifications@github.com&gt;
发送时间: 2019年12月27日(周五) 晚上9:22
收件人: "loogg/agile_led"<agile_led@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [loogg/agile_led] agile_led_create可能导致的内存泄漏问题和链表的创建 (#2)



如果同一个pin，多次调用agile_led_create，因为agile_led_t *led = (agile_led_t *)rt_malloc(sizeof(agile_led_t));调用之前没有判断pin是否被占用，会导致再次对该pin执行creat，而上一次create的led内存未被释放掉，所以可能导致内存泄漏。
 当然，您在example中首先判断了led是否为NULL，但如果在create内部做好判断并返回相应提示将更加健壮。
 另外，建议led 加入链表放在create中，从链表中删除放在delete中，同时active enable放在start中，disable放在stop中，这样逻辑更清晰。
 button中存在同样问题。
 led的软件我已经修改完了，您要是感兴趣可以传给你看看
